title: Discovery
description: Questions to help the website discovery process
theme: just-the-docs

url: https://nJim.github.io/discovery

aux_links:
  Template Repository: https://github.com/nJim/discovery
